logging:
  level: INFO
  format: "[%(asctime)s] %(levelname)s - %(name)s - %(message)s"
port: 8000
spark:
  masterUrl: spark://localhost:7077
db:
  main:
    driver: postgres
    host: localhost
    port: 5432
    database: postgres
    user: postgres
    password: postgres
s3:
  endpoint: localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: data