logging:
  level: INFO
  format: "[%(asctime)s] %(levelname)s - %(name)s - %(message)s"
port: 8000
spark:
  masterUrl: "local[*]"
db:
  main:
    driver: postgres
    host: localhost
    port: 5432
    database: postgres
    user: postgres
    password: postgres
storage:
  local:
    path: uploads
  s3:
    endpoint: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucket: data